### ISSUE TITLE
MEI viewer fails loading example files

### ISSUE THREAD

**Issue by pfefferniels** [rism-digital/verovio.org#65]
Currently the MEI viewer seems to fail loading the example "Marenzio Madrigal a 5": "Sorry, Verovio failed to process the MEI data", "268942296". I can't see any further hints in the console. I have the same issue with several of my own encodings that were rendering just fine in the previous versions.

**Comment by pfefferniels** [comment]
It seems that multiple `scoreDef`s might cause the problem – removing them (in the Marenzio inside `app/rdg`, in my case a second `mdiv` with a new `scoreDef`) solves it.
I'm not sure if verovio is perhaps supposed to fail in that case, but anyways a proper error message would be helpful.

**Comment by lpugin** [comment]
I cannot reproduce the problem with 3.10.0-dev-db30a4b with Firefox and Chrome on Macos 12.2.1

<img width="1512" alt="image" src="https://user-images.githubusercontent.com/689412/157435876-c958c694-ac31-4327-ba1a-946dd034143d.png">


 Which OS / browser are you using?

**Comment by pfefferniels** [comment]
I'm on Firefox 98.0 on Mac OS 11.3.1 (M1). I'm still getting this error. However, I noticed that in private mode it disappears, so I assume it's a caching issue of the browser (though a weird one …). Sorry!
