### ISSUE TITLE
Dead link on homepage

### ISSUE THREAD

**Issue by craigsapp** [rism-digital/verovio.org#99]
In the infobox on the left topish side of the homepage:

<img width="561" alt="Screenshot 2024-04-23 at 8 24 51 AM" src="https://github.com/rism-digital/verovio.org/assets/3487289/4f4a8e7b-3e20-433b-9c21-3110425d3ed0">

This link does not work:

<img width="525" alt="Screenshot 2024-04-23 at 8 22 10 AM" src="https://github.com/rism-digital/verovio.org/assets/3487289/1be87e56-7f57-4283-816d-40856332bd72">

It points to this URL, which is to a file that no longer exists:

https://www.verovio.org/smufl.xhtml

-------------------

Unrelated, I like the github link on the top right:

<img width="155" alt="Screenshot 2024-04-23 at 8 26 50 AM" src="https://github.com/rism-digital/verovio.org/assets/3487289/85c8dffd-48c2-4fd6-8405-a0dce3387929">

now I don't have to search in the menu for the link to the verovio repository.   But it is a little too larger and looks more like a logo than something that is supposed to be clicked on.  Perhaps make it 10&ndash;20% smaller?

**Comment by lpugin** [comment]
https://github.com/rism-digital/verovio.org/commit/f71d8e3e7520634da27cddd6c807f4a98693943d
